# Generated by Django 4.1 on 2022-08-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_record_olingan_sana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='qaytardi',
            field=models.BooleanField(default=False),
        ),
    ]
